/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Catalogos;

import Utilerias.Conexion;
import Utilerias.Linea;
import Utilerias.Proveedor;
import java.sql.*;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Reportes.Reporte_Productos2;


/**
 *
 * @author JossuéEslí
 */
public class Productos extends javax.swing.JFrame {
    
    Conexion conexionProductos;
    /**
     * Creates new form Lineas
     */
    public Productos() {
        initComponents();
        conexionProductos = new Conexion();
        conexionProductos.Open();
        conexionProductos.EjecutarSQL("SELECT id, codigo, nombre, precio_costo, precio_venta, stock, Linea_id, Proveedor_id FROM Producto");
        
        //Llamar a metodo para cargar los datos a la tabla
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_primero = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_refrescar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        text_patron = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lineas");
        setResizable(false);

        jToolBar1.setRollover(true);

        btn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/First.png"))); // NOI18N
        btn_primero.setToolTipText("ir al primer registro");
        btn_primero.setFocusable(false);
        btn_primero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_primero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeroActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_primero);

        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/Anterior.png"))); // NOI18N
        btn_anterior.setToolTipText("ir al anterior");
        btn_anterior.setFocusable(false);
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_anterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_anterior);

        btn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/Next.png"))); // NOI18N
        btn_siguiente.setToolTipText("ir al siguiente");
        btn_siguiente.setFocusable(false);
        btn_siguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_siguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_siguiente);

        btn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/End.png"))); // NOI18N
        btn_ultimo.setToolTipText("ir al ultimo");
        btn_ultimo.setFocusable(false);
        btn_ultimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ultimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ultimo);

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/Nuevo.png"))); // NOI18N
        btn_nuevo.setToolTipText("nuevo registro");
        btn_nuevo.setFocusable(false);
        btn_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nuevo);

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/Editar.png"))); // NOI18N
        btn_editar.setToolTipText("editar registro");
        btn_editar.setFocusable(false);
        btn_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_editar);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/Baja.png"))); // NOI18N
        btn_eliminar.setToolTipText("eliminar registro");
        btn_eliminar.setFocusable(false);
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_eliminar);

        btn_refrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalogos/refresh.png"))); // NOI18N
        btn_refrescar.setToolTipText("refrescar");
        btn_refrescar.setFocusable(false);
        btn_refrescar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_refrescar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrescarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_refrescar);

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print2.png"))); // NOI18N
        btn_imprimir.setFocusable(false);
        btn_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_imprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_imprimir);

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Codigo", "Nombre", "Precio Costo", "Precio Venta", "Stock", "Linea", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        jLabel1.setText("Buscar");

        text_patron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_patronActionPerformed(evt);
            }
        });

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_patron, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_patron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ok))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // codigo necesario para la insercion:
        Producto dlg;
        dlg = new Producto();
        
        dlg.configurarPara("INSERTAR");
        dlg.setTitle("Insertar producto");
        dlg.enlace = conexionProductos;
        dlg.padre = this;
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // Codigo necesario para eliminar registros:
        Producto dlg;
        dlg = new Producto();
        
        dlg.configurarPara("ELIMINAR");
        dlg.setTitle("Eliminar articulo");
        dlg.enlace = conexionProductos;
        dlg.padre = this;
        
         //Recuperamos el registro activo en el JTable
        int registroActivo = tableProductos.getSelectedRow();
        
        if(registroActivo==-1){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun registro", 
                                          "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Vector registro = null;
        DefaultTableModel modelo;
        
        modelo = (DefaultTableModel)tableProductos.getModel();
        
        //Extrar el vector del JTable
        registro = (Vector)modelo.getDataVector().elementAt(registroActivo);
        dlg.cargarCampos(registro.elementAt(0).toString());
                        
        dlg.setVisible(true);
        dlg.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void text_patronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_patronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_patronActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // aqui se codifica el patron de busqueda:
        String patron;
        patron = "SELECT * FROM Producto "+
                 "WHERE nombre LIKE '%"+text_patron.getText()+"%'";
        conexionProductos.EjecutarSQL(patron);
        cargarTabla();
        
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeroActionPerformed
        // ir al primer registro
        int registros = 0;
        registros = tableProductos.getRowCount();
        if(registros == 0){
            JOptionPane.showMessageDialog(null, "No hay registros capturados");
            return;
        }else{
            tableProductos.changeSelection(0, 0, false, false); //se posiciona en el jtable en esa posicion
            
        }
    }//GEN-LAST:event_btn_primeroActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        // ir al ultimo registro:
        int registros = 0;
        registros = tableProductos.getRowCount();
        if(registros == 0){
            JOptionPane.showMessageDialog(null, "No hay registros capturados");
            return;
        }else{
            tableProductos.changeSelection((registros-1), 0, false, false);
        }
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        // ir al registro anterior:
        int registros = 0;
        registros = tableProductos.getRowCount();
        if(registros == 0){
            JOptionPane.showMessageDialog(null, "No hay registros capturados");
            return;
        }
        registros = tableProductos.getSelectedRow();
        if(registros == 0){
            JOptionPane.showMessageDialog(null, "No es posible desplazarse más");
        }else{
            tableProductos.changeSelection(registros-1, 0, false, false);
        }
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // ir al siguiente registro: aqui me quedé
        int registros = 0;
        registros = tableProductos.getRowCount();
        if(registros == 0){
            JOptionPane.showMessageDialog(null, "No hay registros capturados");
            return;
        }
        registros = tableProductos.getSelectedRow();
        if(registros == (tableProductos.getRowCount()-1)){
            JOptionPane.showMessageDialog(null, "No es posible desplazarse más");
        }else{
            tableProductos.changeSelection(registros+1, 0, false, false);
        }
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // Llamada al dialogo en modo de edicion:
        Producto dlg;
        
        dlg = new Producto();
        dlg.configurarPara("EDITAR");
        dlg.setTitle("Editar Articulo");
        dlg.enlace = conexionProductos;
        dlg.padre = this;
        
        //Recuperamos el registro activo en el JTable
        int registroActivo = tableProductos.getSelectedRow();
        
        if(registroActivo==-1){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun registro", 
                                                 "Mensaje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Vector registro = null;
        DefaultTableModel modelo;
        
        modelo = (DefaultTableModel)tableProductos.getModel();
        
        //Extrar el vector del JTable
        registro = (Vector)modelo.getDataVector().elementAt(registroActivo);
        dlg.cargarCampos(registro.elementAt(0).toString());
                        
        dlg.setVisible(true);
        dlg.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrescarActionPerformed
        // refrescar tabla:
        btn_ok.doClick();
    }//GEN-LAST:event_btn_refrescarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
        new Reporte_Productos2();
    }//GEN-LAST:event_btn_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_primero;
    private javax.swing.JButton btn_refrescar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField text_patron;
    // End of variables declaration//GEN-END:variables
    public void cargarTabla(){
        tableProductos.getColumnModel().getColumn(0).setPreferredWidth(20);
        tableProductos.getColumnModel().getColumn(1).setPreferredWidth(20);
        tableProductos.getColumnModel().getColumn(2).setPreferredWidth(150);
        
        DefaultTableModel gridProductos = (DefaultTableModel) tableProductos.getModel();
        gridProductos.setNumRows(0);
        
        try{
            while(conexionProductos.datos.next()){
                gridProductos.addRow(new Object[]{conexionProductos.datos.getString("id"),
                                                  conexionProductos.datos.getString("codigo"),
                                                  conexionProductos.datos.getString("nombre"),
                                                  conexionProductos.datos.getString("precio_costo"),
                                                  conexionProductos.datos.getString("precio_venta"),
                                                  conexionProductos.datos.getString("stock"),
                                                  conexionProductos.datos.getString("Linea_id"),
                                                  conexionProductos.datos.getString("Proveedor_id")});
                                                                                          
            }
        }
        catch(SQLException Error){
            JOptionPane.showMessageDialog(null, "Error", Error.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }
}